log_format json escape=json '{"time":"$time_local",'
    '"host":"$remote_addr",'
    '"forwardedfor":"$http_x_forwarded_for",'
    '"req":"$request",'
    '"status":"$status",'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"body_bytes":$body_bytes_sent,'
    '"referer":"$http_referer",'
    '"ua":"$http_user_agent",'
    '"request_time":$request_time,'
    '"cache":"$upstream_http_x_cache",'
    '"runtime":"$upstream_http_x_runtime",'
    '"response_time":"$upstream_response_time",'
    '"vhost":"$host"}';

server {
    listen       80;
    server_name  localhost;

    # TODO: 最後に消す
    access_log  /var/log/nginx/access.json json_logs;
    location /status {
        stub_status on;
    }
}
